### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by rominaappierdo** [xypan1232/IPMiner#8]
Hello and thank you for sharing your amazing work.

I would like to know if, when I run this kind of command

```
python2.7 IPMiner.py -dataset=RPI1807
```
am I getting the performance of the model trained on RPI1807 and cross-validated on RPI1807 or am  getting the performance of the model trained on RPI488 and tested on RPI1807?

**Comment by xypan1232** [comment]
the model is trained on RPI1807 and cross-validated on RPI1807.

**Comment by rominaappierdo** [comment]
Thank you very much!
