### ISSUE TITLE
need help please

### ISSUE THREAD

**Issue by rominaappierdo** [xypan1232/IPMiner#9]
Hello and thank you for sharing your work.

I would like to know if it was proper to run the command

```
python2.7 IPMiner.py -dataset=RPI1807

```

after modifing the input files in the ncRNA-protein directory. 
I'll explain it better: I have a dataset of my concern, and would like to train and cross validate IPMiner on it. So I wanted to go down this route: given the interaction in my dataset, formatting them in files of the same setting of your RPI1807 files. Then I would rename them as [RPI1807_PositivePairs.csv, RPI1807_NegativePairs.csv, RPI1807_RNA_seq.fa, RPI1807_protein_seq.fa] and move them in the ncRNA-protein directory.

Then I would run the abovementioned command.

Is this accettable?

Thank you in advance

**Comment by xypan1232** [comment]
Yes, it is OK, you just prepare the data the same as the four files of RPI1807.

**Comment by rominaappierdo** [comment]
Thank you so much!
